#! /usr/bin/env python

import sys
import os

import cyres

include_path = os.path.dirname(cyres.__file__)
include_path = os.path.join(include_path, "src")

command = "cython -I {0} {1}".format(include_path, ' '.join(sys.argv[1:]))
os.system(command)
